# Generated by Django 4.0.5 on 2022-06-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20220609_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, to='user_profile.follow'),
        ),
    ]
