# Generated by Django 4.0.5 on 2022-06-16 07:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
