# Generated by Django 4.0.5 on 2022-06-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_part', '0008_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
