# Generated by Django 4.0.5 on 2022-06-12 14:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notificaiton',
            new_name='Notification',
        ),
    ]
